### ISSUE TITLE
XSS because of facebook API

### ISSUE THREAD

**Issue by bossen** [OpenSourceAalborg/os-aalborg.dk#2]
The facebook api does not sanitize it contents.
This makes the site vulnerable to persistent xss, by creating an event with a payload.

The payload can be used to places. At `http://ẁww.os-aalborg.dk/` and at `http://www.os-aalborg.dk/feed.php`

`http://www.os-aalborg.dk/feed.php` should be served as text/json using header('Content-Type: application/json');

For `http://www.os-aalborg.dk/` we need to create a javascript function like
```
function escapeHTML (unsafe_str) {
    return unsafe_str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/\"/g, '&quot;')
      .replace(/\'/g, '&#39;')
      .replace(/\//g, '&#x2F;')
}
```
and use it every time we insert content from the event.

**Comment by palmelund** [comment]
Fixed
